spring:
  application:
    name: looper
  datasource:
    url: jdbc:postgresql://localhost:5433/looperdb_main_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: true
    s3:
      bucket: looper-dev-image-s3
      profile-image-prefix: profile-images
      initialize-profile-images: false

kakao:
  client-id: ${KAKAO_REST_API_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}


jwt:
  secret: ${JWT_SECRET}

fastapi:
  base-url: http://localhost:8000 