spring:
  config:
    import: optional:dotenv:.env
  application:
    name: looper
    mode: ${DEV_ENV:development}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/looperdb_main_dev}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update

server:
  forward-headers-strategy: framework

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: true
    s3:
      bucket: ${S3_BUCKET:looper-dev-image-s3}
      profile-image-prefix: ${IMAGE_PREFIX:profile-images}
      initialize-profile-images: false

kakao:
  client-id: ${KAKAO_REST_API_KEY}

jwt:
  secret: ${JWT_SECRET}

fastapi:
  base-url: ${FASTAPI_BASE_URL:http://localhost:8000}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always  # 필요 시 의존성 상태를 자세히 표시
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.1
    description: Looper API 서버

cookie:
  secure: ${USE_HTTPS:false}